context:
  version: "0.20261004"

package:
  name: ccls
  version: ${{ version }}

source:
  url: https://github.com/MaskRay/ccls/archive/refs/tags/${{ version }}.tar.gz
  sha256: 8e022718ac8d54aef36cd728a177ad036994d7abf535941b948ae14d1a9085dd

build:
  number: 0
  skip:
    - win

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake
    - ninja
  host:
    - clangdev 21.*
    - llvmdev 21.*
    - rapidjson
  run:
    - libclang-cpp21.1
    - libllvm21

tests:
  - script:
      - ccls --help

about:
  homepage: https://github.com/MaskRay/ccls
  summary: C/C++/Objective-C language server
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - user202729
